### ISSUE TITLE
About other self-supervised framework

### ISSUE THREAD

**Issue by EBGU** [tinapan-pt/VideoMoCo#2]
Hi!

I read your paper and it is really great! I am also working with contrast learning applied to videos, and I am trying frameworks that don't need negative samples(like simsiam). I wonder if you have tried those frameworks? My networks suffered from either collapse or no convergence, so I just want to discuss with you.

Thank you!

**Comment by tinapan-pt** [comment]
Simsiam is indeed easier to collapse, you can refer to the methods of preventing collapse in the article "Exploring Simple Siamese Representation Learning".
